name: Compilar Lite DLNA (.exe)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 1. Descargar Código
      uses: actions/checkout@v4

    - name: 2. Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: 3. Inicializar Módulo e Instalar Dependencias
      run: |
        go mod init mini_dlna
        go get ://github.com
        go mod tidy

    - name: 4. Compilar para Windows (.exe)
      env:
        GOOS: windows
        GOARCH: amd64
      run: |
        mkdir dist
        go build -ldflags="-s -w" -o dist/mini_dlna_player.exe main.go

    - name: 5. Crear Release y Subir el ejecutable .exe
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.\${{ github.run_number }}
        name: Lite DLNA Player v1.0.\${{ github.run_number }}
        body: |
          ### ¡Programa Lite Compilado! 🚀
          Descarga el archivo `.exe` para usarlo directamente en Windows. No requiere instalación.
        files: dist/mini_dlna_player.exe
